'use strict';

const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
const root=path.resolve(__dirname,'..');
const files=['data/life-actions.js','data/scenarios.js','data/petitions.js','data/emergent.js','data/private-incidents.js','data/depth-systems.js','data/grand-systems.js','data/living-world.js','data/private-world.js','data/crown-depth.js','data/sovereign-systems.js','game.js'];

class FakeElement{
 constructor(){this.innerHTML='';this.textContent='';this.value='';this.dataset={};this.children=[];this.open=false;this.className='';this.classList={add(){},remove(){},contains(){return false}}}
 append(){ } appendChild(){ } remove(){ } insertAdjacentElement(){ } insertAdjacentHTML(){ }
 showModal(){this.open=true} close(){this.open=false} addEventListener(){ } matches(){return false} closest(){return null}
}
const elements=new Map(),element=key=>{if(!elements.has(key))elements.set(key,new FakeElement());return elements.get(key)};
const store=new Map();
const context={
 structuredClone,Intl,Date,Math,JSON,Number,String,Object,Array,Set,Map,RegExp,Error,
 console,setTimeout(){return 0},clearTimeout(){},requestAnimationFrame(fn){fn()},
 localStorage:{getItem:k=>store.get(k)||null,setItem:(k,v)=>store.set(k,String(v)),removeItem:k=>store.delete(k)},
 document:{querySelector:element,querySelectorAll(){return []},getElementById:id=>elements.get('#'+id)||null,createElement(){return new FakeElement()},createTextNode(v){return String(v)},addEventListener(){},body:element('body')},
 window:{scrollTo(){}},
};
context.globalThis=context;
let source=files.map(f=>fs.readFileSync(path.join(root,f),'utf8')).join('\n');
source+='\n;globalThis.__runtime={state:()=>state,view:n=>{state.view=n;render(false);return document.querySelector("#view").innerHTML},goods:()=>goodsMarketPanel(),command:x=>parseCommand(x),tick:()=>{depthSystemsTurn();grandSystemsTurn();livingTurn();privateWorldTurn();crownDepthTurn()},step:()=>{state.turn++;depthSystemsTurn();grandSystemsTurn();livingTurn();privateWorldTurn();crownDepthTurn();normalizeState()},calendar:()=>advanceCalendar(),economy:()=>economySimulationTick(),world:()=>worldSimulationTick(),grand:()=>ensureGrand(),living:()=>ensureLiving(),privateWorld:()=>ensurePrivateWorld(),crown:()=>ensureCrownDepth(),privatePath:x=>privateWorldPathAction(x),privateContact:x=>privateWorldContactAction(x),privateVenture:x=>privateWorldVentureAction(x),forceScandal:x=>privateWorldStartScandal(x,true),privateScandal:x=>privateWorldScandalAction(x),privateLegacy:x=>privateWorldLegacyAction(x),household:x=>crownHouseholdAction(x),festival:x=>crownFestivalAction(x),festivalFirst:()=>{let f=ensureCrownDepth().festival.active,e=CROWN_FESTIVAL_EVENTS.find(x=>x.id===f.events[f.index]);return e.choices[0][0]},rival:x=>crownRivalAction(x),secret:x=>crownSecretAction(x),palace:x=>crownPalaceAction(x),society:x=>crownSocietyAction(x),customLaw:x=>crownLawAction(x),expedition:x=>crownExpeditionAction(x),legacy:()=>crownLegacySnapshot(),annex:id=>grandAnnexProvince(id),law:x=>grandGovernmentLawAction(x),plan:x=>grandCampaignPlanAction(x),build:x=>grandStartDevelopment(x),provinceTick:()=>grandProvinceTick(),decision:(a,b,m)=>recordDecision(a,b,m),battle:id=>depthBattleModifier(id),treaty:x=>livingTreatyAction(x),ratify:(n,p)=>livingRatifyTreaty(n,livingTreatyDraft(n,p)),capital:x=>livingCapitalAction(x),journeySetup:x=>livingJourneySetup(x),journey:x=>livingJourneyAction(x),tradition:x=>livingTraditionAction(x),civil:()=>livingStartCivilWar(true),civilAction:x=>livingCivilAction(x),chain:x=>livingChainAction(x)};';
source+='\n;Object.assign(globalThis.__runtime,{tick:()=>{depthSystemsTurn();grandSystemsTurn();livingTurn();privateWorldTurn();crownDepthTurn();sovereignTurn();normalizeState()},step:()=>{state.turn++;depthSystemsTurn();grandSystemsTurn();livingTurn();privateWorldTurn();crownDepthTurn();sovereignTurn();normalizeState()},sovereign:()=>ensureSovereign(),sovereignTurn:()=>sovereignTurn(),directorTurn:()=>sovereignDirectorTurn(),childrenTurn:()=>sovereignChildrenTurn(),tradeTurn:()=>sovereignTradeTurn(),cultureTurn:()=>sovereignCultureTurn(),director:x=>sovereignDirectorAction(x),child:x=>sovereignChildAction(x),peace:x=>sovereignPeaceAction(x),trade:x=>sovereignTradeAction(x),culture:x=>sovereignCultureAction(x),chapter:x=>sovereignChapterAction(x),chapterTurn:x=>sovereignChapterTurn(x),pace:()=>sovereignPaceUpcoming(),scenario:x=>chooseScenario(x),petition:x=>choosePetition(x),privateIncident:x=>choosePrivateIncident(x),map:()=>mapSvg()});';
vm.runInNewContext(source,context,{filename:'valdoria-runtime.js'});
const api=context.__runtime;
for(const [view,needles] of [['realm',['STAATSORDNUNG','INNERER FRIEDEN','DER RHYTHMUS DER HERRSCHAFT','EINE GESELLSCHAFT IN BEWEGUNG']],['finances',['KÖNIGLICHE SCHATZKAMMER','WARENSTRÖME AUF DER KARTE','PRODUKTIONSKETTEN DES REICHES']],['council',['VERFASSUNG UND REICHSGESETZE','DIE KULTUR VON FALKENKRONE','DER KÖNIGLICHE HAUSHALT','DER KÖNIGLICHE GESETZESBAUKASTEN','DIE SCHWARZE CHRONIK','MENSCHEN, DIE SICH GEGENSEITIG ERINNERN']],['military',['KRIEGSRAT UND OBERBEFEHL']],['diplomacy',['DER GROSSE FRIEDEN','DIE WELT HANDELT WEITER','KRONEN MIT GESICHTERN','EXPEDITIONEN JENSEITS DER BEKANNTEN SEE','VERTRÄGE, DIE DIE WELT BINDEN','HERRSCHERHÄUSER DER WELT']],['projects',['EPOCHEN UND ERNEUERUNG','FALKENKRONE WÄCHST MIT DER DYNASTIE','DIE ZEIT VERÄNDERT DAS SPIEL']],['private',['LEBENSWEGE OHNE DREHBUCH','DER VERBORGENE HOF','NÄCHTE OHNE KRONE','GERÜCHTE, BEWEISE UND VERSPRECHEN','DIE NÄCHSTE GENERATION','FESTE, TURNIERE UND NÄCHTE DES HOFES','WO DER KÖNIG LEBT','FALKENKRONE BEGEHEN','TRADITIONEN DES HAUSES VALEDOR']],['chronicle',['DIE STRUKTUR EURER HERRSCHAFT','DIE LEBENDIGE DYNASTIE','DIE BÜCHER DER HERRSCHAFT','WAS DIE KRONE MIT DEM MENSCHEN MACHT','FÜNF STIMMEN ÜBER JEDE HERRSCHAFT']]]){let html=api.view(view);for(const needle of needles)assert.match(html,new RegExp(needle),`${view} bindet „${needle}“ nicht ein`)}
assert.match(api.goods(),/WAREN, VORRÄTE UND HANDELSWEGE/,'Die Warenwirtschaft lässt sich im Finanzbereich nicht rendern');
assert.equal(api.command('Setze den Forschungsschwerpunkt auf Seemacht.').ok,true,'Freie Befehle steuern die neue Forschung nicht');
assert.equal(api.command('Kaufe Eisen für die königlichen Speicher.').ok,true,'Freie Befehle steuern den Warenmarkt nicht');
assert.equal(api.command('Mache das Reich irgendwie besser.').ok,false,'Ein unklarer freier Befehl darf nicht stillschweigend irgendetwas ausführen');
const s=api.state(),beforeKnowledge=s.depth.innovation.knowledge,beforeWorld=Object.values(s.depth.world).reduce((n,w)=>n+w.progress,0),beforeStocks=Object.values(s.depth.economy.goods).reduce((n,g)=>n+g.stock,0);
assert.equal(api.command('Beende den Handel mit Ravengar.').ok,true,'Natürlich formulierter Handelsstopp wird nicht verstanden');
assert.equal(s.countryPolicy.Ravengar.embargo,true,'Der erkannte Handelsstopp verändert den Vertrag nicht');
assert.equal(api.command('Öffne die Häfen und senke die Zölle.').ok,true,'Zusammengehörige Hafen- und Zollpolitik wird fälschlich geteilt');
assert.equal(s.financePolicy.customs,'open','Der Freitextbefehl öffnet die Häfen nicht');
assert.equal(api.command('Gehe in Vaters Arbeitszimmer und trauere.').ok,true,'Ein natürlicher privater Satz wird nicht als ein Weg erkannt');
const fundedReserve=s.reserve,fundedBuilding=s.buildingFund,grainUnrest=s.regions.ravengar.unrest,decisionsBeforeFunding=s.decisions.length;
s.reserve=0;s.pendingScenario='grain';api.scenario('grain:subsidy');
assert.equal(s.pendingScenario,'grain','Eine unbezahlbare Entscheidung wurde trotzdem abgeschlossen');
assert.equal(s.regions.ravengar.unrest,grainUnrest,'Eine unbezahlbare Entscheidung erhielt kostenlose Vorteile');
assert.equal(s.decisions.length,decisionsBeforeFunding,'Eine abgelehnte Finanzierung wurde als Entscheidung protokolliert');
s.buildingFund=0;s.pendingScenario='earthquake';const islandInfrastructure=s.regions.islands.infrastructure;api.scenario('earthquake:engineers');
assert.equal(s.pendingScenario,'earthquake','Eine gekappte Fondsausgabe wurde trotzdem abgeschlossen');
assert.equal(s.regions.islands.infrastructure,islandInfrastructure,'Math.max-Kosten erlauben noch kostenlose Vorteile');
s.reserve=fundedReserve;s.buildingFund=fundedBuilding;s.pendingScenario='grain';
const startAge=s.life.age,startYear=s.year;api.calendar();assert.equal(s.life.age,startAge,'Nach nur einer Runde darf der König noch nicht altern');api.calendar();assert.equal(s.life.age,startAge+1,'Nach zwei Runden muss genau ein Lebensjahr vergangen sein');assert.equal(s.year,startYear+1,'Der Kalender braucht exakt zwei Runden pro Jahr');
assert.ok(api.living().people.length>=14,'Familie, Rat und große Häuser fehlen in der lebendigen Personenwelt');
const memoriesBefore=api.living().people.reduce((n,p)=>n+p.memories.length,0);api.decision('Hilfe für hungernde Familien','Die Krone schützt Kinder und versorgt die Armen.',{kind:'private'});assert.ok(api.living().people.reduce((n,p)=>n+p.memories.length,0)>memoriesBefore,'Entscheidungen hinterlassen keine persönlichen Erinnerungen');
api.tick();assert.ok(Object.keys(api.living().relations).length>=2,'Hofpersonen entwickeln untereinander keine Beziehungen');
assert.equal(api.capital('move:archive'),true,'Der König kann sich nicht durch Falkenkrone bewegen');assert.equal(api.capital('act:research'),true,'Hauptstadtorte besitzen keine wirklichen Handlungen');
assert.equal(api.tradition('education:books'),true,'Eine neue Dynastietradition lässt sich nicht prägen');assert.equal(api.living().traditions.adopted.education,'books','Dynastietraditionen bleiben nicht im Spielzustand');
assert.equal(api.treaty('Lysara:treaty:toggle:knowledge'),true,'Vertragsklauseln lassen sich nicht einzeln verhandeln');assert.ok(api.living().drafts['treaty:Lysara'].clauses.includes('knowledge'),'Die ausgewählte Klausel fehlt im Vertragsentwurf');
s.diplo.Lysara={war:true,treaty:'none'};api.living().drafts['peace:Lysara']={country:'Lysara',peace:true,clauses:['prisoners','nonaggression','knowledge'],duration:10,lastChanged:s.turn};api.ratify('Lysara',true);assert.equal(s.diplo.Lysara.war,false,'Ein ratifizierter Friedensvertrag beendet den Krieg nicht');assert.ok(api.living().treaties.some(t=>t.country==='Lysara'&&t.status==='active'),'Der Friedensvertrag besitzt keine dauerhafte Laufzeit');
assert.equal(api.grand().houses.length,6,'Es existieren nicht sechs eigenständige rivalisierende Häuser');
assert.equal(Object.keys(api.grand().government.laws).length,7,'Die Verfassung besitzt nicht alle Gesetzesfelder');
assert.equal(Object.keys(api.grand().provinces).length,8,'Die Provinzidentitäten decken die Karte nicht ab');
s.life.age=20;s.life.regency=false;s.reserve=60000000;s.militaryFund=20000000;s.buildingFund=50000000;s.grand.government.mandate=80;
assert.equal(api.culture('access:open'),true,'Die Hofkultur lässt sich nicht bewusst verändern');
assert.equal(api.sovereign().culture.policies.access,'open','Die gewählte Hofkultur bleibt nicht im Spielstand');
const peopleBeforeCulture=s.factions.people;api.cultureTurn();assert.ok(s.factions.people>peopleBeforeCulture,'Hofkultur verändert Gesellschaft und Politik nicht pro Runde');
s.life.children.push({name:'Lucen',age:8,education:12,traitId:'curious'});api.sovereign();const childProfile=Object.values(api.sovereign().children.profiles)[0];
assert.ok(childProfile?.goal&&childProfile?.temper,'Königliche Kinder besitzen keine eigene Persönlichkeit und Ziele');
assert.equal(api.child(`education:${childProfile.id}:diplomacy`),true,'Ein individueller Ausbildungsweg lässt sich nicht setzen');
assert.equal(api.child(`autonomy:${childProfile.id}`),true,'Einem Kind lässt sich kein eigener Lebensweg erlauben');
const autonomyAfterChoice=childProfile.autonomy,confidenceBeforeChildTurn=childProfile.confidence;s.turn++;api.childrenTurn();
assert.ok(childProfile.confidence>confidenceBeforeChildTurn&&childProfile.autonomy===autonomyAfterChoice,'Kinder entwickeln sich nicht autonom über die Zeit');
s.diplo.Aurelia={war:true,treaty:'none'};api.tradeTurn();assert.equal(api.sovereign().trade.routes.Aurelia.status,'war','Krieg unterbricht den sichtbaren Warenstrom nicht');
s.mapMode='trade';assert.match(api.map(),/sovereign-trade-layer visible/,'Der Handelsmodus zeigt keine animierten Warenwege auf der Karte');s.diplo.Aurelia.war=false;
const tradeFundBefore=s.tradeFund;assert.equal(api.trade('subsidize:Lysara'),true,'Eine Handelsroute lässt sich nicht gezielt fördern');assert.equal(s.tradeFund,tradeFundBefore-1200000,'Routensubventionen kosten den vorgesehenen Handelsfonds nicht');
s.diplo.Nordhaven={war:true,treaty:'none',campaign:{startedTurn:s.turn,initialEnemy:30000,ownLosses:800,enemyLosses:24000,battles:6,victories:6}};s.relations.Nordhaven=80;s.regions.nordhaven.garrison=12;s.countryPolicy.Nordhaven={occupied:true};s.depth.world.Nordhaven.power=10;
for(const code of ['territory:annex','reparations:none','military:none','trade:access','prisoners:return','ruler:restore','guarantee:truce']){let[k,v]=code.split(':');assert.equal(api.peace(`Nordhaven:term:${k}:${v}`),true,`Friedensklausel ${k} lässt sich nicht verhandeln`)}
for(let tries=0;s.diplo.Nordhaven.war&&tries<12;tries++){s.turn+=2;api.peace('Nordhaven:ratify')}
assert.equal(s.diplo.Nordhaven.war,false,'Ein überwältigend unterstützter Friedenskongress beendet den Krieg nicht');
assert.equal(s.countryPolicy.Nordhaven.annexed,true,'Die im Friedensvertrag beschlossene Einverleibung verändert Karte und Provinz nicht');
let director=api.sovereign().director;director.lastSituation=-99;for(let tries=0;!api.sovereign().director.situation&&tries<8;tries++){s.turn++;api.directorTurn()}director=api.sovereign().director;
assert.ok(director.situation?.sources,'Der Dramaturgie-Regisseur erzeugt keine kontextuelle Lage aus früheren Entscheidungen');
const arcChoice={war:'limits',economy:'ration',family:'listen',society:'assembly',court:'truth',exploration:'science',formation:'learn'}[director.situation.arc];assert.equal(api.director(arcChoice),true,'Ein Herrschaftsbogen lässt sich nicht sinnvoll entscheiden');assert.equal(api.sovereign().director.situation,null,'Eine entschiedene Regiesituation bleibt offen');
api.decision('Fünf Jahre des Aufbaus','Häfen, Familie und Hof wurden sichtbar verändert.',{kind:'development'});api.sovereign().lastChapterYear=s.year-5;const chapterCount=api.sovereign().chapters.length;assert.equal(api.chapterTurn(false),true,'Nach fünf Jahren entsteht kein illustriertes Herrschaftskapitel');assert.equal(api.sovereign().chapters.length,chapterCount+1,'Das Fünfjahreskapitel bleibt nicht in der Chronik');
const oldPending={scenario:s.pendingScenario,private:s.pendingPrivateIncident,consequences:s.pendingConsequences,emergent:s.emergent,petitions:s.petitions};api.sovereign().director.mode='focused';s.pendingScenario='grain';s.pendingPrivateIncident='father_room';s.pendingConsequences=[{id:'test'}];s.emergent={id:'test'};s.petitions=[{id:'one',done:false},{id:'two',done:false}];api.pace();assert.ok(api.sovereign().director.backlog.length>=2,'Die Entscheidungs-Triage verschiebt Überlastung nicht in eine sichtbare Warteschlange');Object.assign(s,{pendingScenario:oldPending.scenario,pendingPrivateIncident:oldPending.private,pendingConsequences:oldPending.consequences,emergent:oldPending.emergent,petitions:oldPending.petitions});api.sovereign().director.mode='balanced';
assert.ok(Object.keys(api.privateWorld().contacts).length>=9,'Der verborgene Hof besitzt nicht genügend unterschiedliche Beziehungen');
assert.equal(api.privatePath('libertine'),true,'Ein eigener unkonventioneller Lebensweg lässt sich nicht einschlagen');
s.private.actionPoints=4;assert.equal(api.privateContact('meet:harbor_voice'),true,'Eine neue persönliche Bekanntschaft lässt sich nicht beginnen');api.privateWorld().contacts.harbor_voice.affection=45;assert.equal(api.privateContact('deepen:harbor_voice'),true,'Eine Bekanntschaft kann nicht zu einer langfristigen privaten Beziehung werden');assert.equal(api.privateWorld().contacts.harbor_voice.status,'intimate','Die Beziehung besitzt keinen dauerhaften Zustand');
s.private.actionPoints=3;assert.equal(api.privateContact('promise:harbor_voice'),true,'Eine private Beziehung kann kein echtes Versprechen erzeugen');assert.equal(api.privateContact('fulfill:harbor_voice'),true,'Ein gegebenes Versprechen kann nicht bewusst eingelöst werden');assert.equal(api.privateWorld().contacts.harbor_voice.promises.at(-1).kept,true,'Das erfüllte Versprechen bleibt nicht in der gemeinsamen Geschichte');
s.private.actionPoints=3;assert.equal(api.privateVenture('start:underground_ball'),true,'Eine mehrstufige private Unternehmung beginnt nicht');assert.equal(api.privateVenture('resolve:underground_ball:dance'),true,'Die private Unternehmung lässt sich nicht individuell entscheiden');assert.ok(api.privateWorld().ventureHistory.length,'Ungewöhnliche Nächte hinterlassen keine Geschichte');
api.privateWorld().exposure=85;api.privateWorld().evidence=60;assert.equal(api.forceScandal('masquerade'),true,'Ein privater Skandal lässt sich nicht aus den gesammelten Spuren erzeugen');assert.equal(api.privateScandal('confess'),true,'Die Skandalkrise besitzt keine spielbare Reaktion');assert.ok(api.privateWorld().scandalHistory.length,'Ein bewältigter Skandal verschwindet aus der Biografie');
s.private.purse=1000000;api.privateWorld().pendingLegacy={contact:'harbor_voice',childName:'Maris Bell',bornYear:s.year};assert.equal(api.privateLegacy('protect'),true,'Eine private Abstammungsfolge lässt sich nicht verantwortlich entscheiden');assert.equal(api.privateWorld().hiddenChildren.length,1,'Die verborgene Seitenlinie bleibt nicht über Runden bestehen');
assert.equal(Object.keys(api.crown().household.roles).length,8,'Der persönliche Haushalt besitzt nicht alle acht Ämter');assert.equal(api.household('appoint:physician:physician'),true,'Eine konkrete Hofperson lässt sich nicht in den persönlichen Haushalt berufen');assert.equal(api.household('consult:physician'),true,'Ein besetztes Haushaltsamt hat keine spielbare Wirkung');
assert.equal(api.festival('type:masquerade'),true,'Der Typ eines großen Hoffests lässt sich nicht planen');assert.equal(api.festival('scale:grand'),true,'Der Umfang eines Hoffests lässt sich nicht festlegen');assert.equal(api.festival('start'),true,'Ein vollständig geplantes Hoffest beginnt nicht');for(let i=0;i<3;i++){assert.ok(api.crown().festival.active?.events[i],'Das Hoffest besitzt keine dreiteilige Ereignisfolge');assert.equal(api.festival('resolve:'+api.festivalFirst()),true,'Eine Hoffestszene lässt sich nicht entscheiden')}assert.equal(api.crown().festival.active,null,'Ein abgeschlossenes Hoffest bleibt fälschlich offen');assert.ok(api.crown().festival.history.length,'Das Hoffest hinterlässt keine Geschichte');
assert.equal(api.rival('write:Lysara'),true,'Eine persönliche Beziehung zu einer fremden Herrscherin lässt sich nicht führen');assert.ok(api.crown().rivals.Lysara.encounters.length,'Die fremde Krone erinnert sich nicht an die Begegnung');
(s.countryPolicy||(s.countryPolicy={})).Lysara={occupied:true};api.step();assert.equal(api.crown().rivals.Lysara.status,'captured','Eine vollständig besiegte Krone gerät nicht in persönliche Gefangenschaft');assert.equal(api.rival('release:Lysara'),true,'Über das Schicksal einer gefangenen Herrscherin lässt sich nicht entscheiden');assert.equal(api.crown().rivals.Lysara.status,'released','Die persönliche Gnade verändert den dauerhaften Status der besiegten Krone nicht');s.countryPolicy.Lysara.occupied=false;
assert.equal(api.palace('build:library'),true,'Ein neuer Palastflügel lässt sich nicht beginnen');api.tick();api.tick();assert.equal(api.crown().palace.rooms.library.level,1,'Der Palastflügel wird nach seiner Bauzeit nicht eröffnet');assert.equal(api.palace('act:library:study'),true,'Ein errichteter Palastraum eröffnet keine eigene Handlung');
api.crown().society.artisans.satisfaction=20;assert.equal(api.society('negotiate:artisans'),true,'Gesellschaftliche Forderungen können nicht ausgehandelt werden');assert.ok(api.crown().society.artisans.satisfaction>20,'Die Verhandlung verändert die betroffene Gruppe nicht');
assert.equal(api.customLaw('field:subject:cities'),true,'Der Geltungsbereich eines eigenen Gesetzes lässt sich nicht setzen');assert.equal(api.customLaw('field:right:access'),true,'Der Inhalt eines eigenen Gesetzes lässt sich nicht setzen');assert.equal(api.customLaw('enact'),true,'Ein vollständig zusammengesetztes Gesetz lässt sich nicht beschließen');assert.ok(api.crown().customLaws.length,'Das eigene Gesetz bleibt nicht in der Rechtsgeschichte');
api.crown().secrets.unshift({id:'test_secret',year:s.year,title:'Ein Brief aus dem Testarchiv',origin:'Laufzeitprüfung',text:'Ein dauerhaftes Geheimnis.',category:'court',leverage:50,exposure:5,used:null});assert.equal(api.secret('reveal:test_secret'),true,'Ein bekanntes Geheimnis lässt sich nicht bewusst veröffentlichen');assert.equal(api.crown().secrets[0].used,'revealed','Die Verwendung eines Geheimnisses bleibt nicht gespeichert');
assert.equal(api.expedition('captain:admiral'),true,'Eine Expedition erhält keinen Kapitän');assert.equal(api.expedition('purpose:science'),true,'Eine Expedition erhält keinen Forschungsauftrag');assert.equal(api.expedition('route:north'),true,'Eine Expedition erhält keine Route');assert.equal(api.expedition('start'),true,'Eine vollständig ausgerüstete Expedition läuft nicht aus');for(let guard=0;api.crown().expedition.active&&guard<20;guard++){api.tick();let ev=api.crown().expedition.active?.pendingEvent;if(ev)assert.equal(api.expedition('event:'+ev.choices[0][0]),true,'Ein Expeditionszwischenfall lässt sich nicht entscheiden')}assert.equal(api.crown().expedition.active,null,'Die Expedition kehrt nach ihrer geplanten Dauer nicht zurück');assert.ok(api.crown().expedition.discoveries.length,'Die Expedition hinterlässt keine Entdeckung oder Verlustgeschichte');
for(let i=0;i<8;i++)api.decision('Ein neues Freiheitsgesetz','Gemeinden erhalten Bildung, Recht und überprüfbaren Schutz.',{kind:'realm'});assert.ok(api.crown().traits.length,'Wiederholte Herrscherentscheidungen erzeugen keine prägende Eigenschaft');assert.equal(Object.keys(api.legacy().perspectives).length,5,'Das Vermächtnis enthält nicht fünf unterschiedliche gesellschaftliche Stimmen');
assert.equal(api.chain('arms:invest'),true,'Produktionsketten lassen sich nicht ausbauen');assert.equal(api.living().production.chains.arms.level,2,'Der Ausbau verändert die Produktionskapazität nicht');
assert.equal(api.journeySetup('destination:caerhaven'),true,'Eine Königsreise erhält kein Ziel');assert.equal(api.journeySetup('route:road'),true,'Eine Königsreise erhält keine Route');assert.equal(api.journeySetup('companion:regent'),true,'Eine Königsreise erhält keine Begleitung');assert.equal(api.journey('start:journey'),true,'Die mehrstufige Königsreise beginnt nicht');for(let guard=0;api.living().journey&&guard<6;guard++){let choice=api.living().journey.event.choices[0].id;assert.equal(api.journey('choice:'+choice),true,'Eine Reiseetappe lässt sich nicht entscheiden')}assert.equal(api.living().journey,null,'Die Königsreise kommt nach ihren Etappen nicht ans Ziel');assert.ok(api.living().journeyHistory.length>0,'Die abgeschlossene Reise hinterlässt keine Geschichte');
assert.equal(api.civil(),true,'Eine erzwungene Thronkrise erzeugt keinen Bürgerkrieg');assert.ok(api.living().civilWar?.provinces.length,'Der Bürgerkrieg besitzt keine beteiligten Provinzen');assert.equal(api.civilAction('amnesty'),true,'Im Bürgerkrieg lässt sich keine politische Strategie wählen');
assert.equal(api.law('faith:secular'),true,'Ein gültiges Reichsgesetz lässt sich nicht beschließen');
assert.equal(s.grand.government.laws.faith,'secular','Das neue Glaubensrecht bleibt nicht im Spielstand');
s.diplo.Ravengar={war:true,treaty:'none'};
assert.equal(api.plan('ravengar:route:highland'),true,'Die Marschroute lässt sich nicht planen');
assert.equal(api.plan('ravengar:doctrine:shock'),true,'Die Feldzugsdoktrin lässt sich nicht planen');
assert.equal(api.plan('ravengar:objective:capital'),true,'Das Kriegsziel lässt sich nicht planen');
assert.equal(api.plan('ravengar:issue:plan'),true,'Der vollständige Feldzugsplan lässt sich nicht besiegeln');
assert.equal(s.grand.campaigns.Ravengar.active,true,'Der besiegelte Feldzugsplan wird nicht aktiv');
assert.ok(Number.isFinite(api.battle('ravengar'))&&api.battle('ravengar')>0,'Feldzugsplan und Wetter ergeben keinen gültigen Kampfmodifikator');
const fortBefore=s.grand.provinces.caerhaven.buildings.fort;
assert.equal(api.build('caerhaven:fort'),true,'Ein Provinzbau lässt sich nicht beginnen');
s.grand.provinces.caerhaven.construction.progress=99;api.provinceTick();
assert.equal(s.grand.provinces.caerhaven.buildings.fort,fortBefore+1,'Der Provinzbau wird nicht fertiggestellt');
for(let i=0;i<6;i++)api.decision('Neue Königsstraße bauen','Schulen, Häfen und Straßen werden gemeinsam ausgebaut.',{kind:'development'});
assert.equal(s.grand.traits.earned.includes('builder'),true,'Wiederholte Entscheidungen erzeugen keinen Herrschercharakter');
api.tick();
assert.ok(s.depth.innovation.knowledge>beforeKnowledge,'Forschung schreitet pro Runde nicht voran');
assert.ok(Object.values(s.depth.world).reduce((n,w)=>n+w.progress,0)>beforeWorld,'Nachbarreiche verfolgen ihre Pläne nicht');
assert.notEqual(Object.values(s.depth.economy.goods).reduce((n,g)=>n+g.stock,0),beforeStocks,'Warenproduktion und Verbrauch laufen nicht');
assert.equal(s.depth.court.length,8,'Hofpersonen gingen im laufenden Spiel verloren');
for(let i=0;i<60;i++)api.step();
assert.ok(s.depth.innovation.unlocked.length>=2,'Langfristige Forschung erzeugt keine Durchbrüche');
assert.ok(s.depth.news.length<=36,'Die erzählten Folgen wachsen unbegrenzt im Speicher');
assert.ok(Object.values(s.depth.world).every(w=>Number.isFinite(w.power)&&w.power>=10&&w.power<=100),'Weltmächte verlassen gültige Wertebereiche');
assert.ok(Object.values(s.depth.economy.goods).every(g=>Number.isFinite(g.stock)&&g.stock>=0&&g.price>=4),'Warenwerte werden nach vielen Runden ungültig');
assert.ok(api.grand().houses.every(h=>Number.isFinite(h.relation)&&h.relation>=0&&h.relation<=100),'Dynastien verlassen nach vielen Runden gültige Wertebereiche');
assert.ok(Object.values(api.grand().provinces).every(p=>p.acceptance>=0&&p.acceptance<=100&&p.harmony>=0&&p.harmony<=100),'Kultur- oder Glaubenswerte werden ungültig');
assert.ok(Object.values(api.crown().society).every(g=>Number.isFinite(g.satisfaction)&&g.satisfaction>=0&&g.satisfaction<=100&&g.radicalism>=0&&g.radicalism<=100),'Gesellschaftliche Gruppen verlassen nach vielen Runden gültige Wertebereiche');
assert.ok(Object.values(api.crown().rivals).every(r=>r.respect>=0&&r.respect<=100&&r.resentment>=0&&r.resentment<=100&&r.bond>=0&&r.bond<=100),'Persönliche Beziehungen zu fremden Kronen werden ungültig');
assert.ok(api.crown().memories.length<=80&&api.crown().customLaws.length<=20,'Erinnerungen oder eigene Gesetze wachsen unbegrenzt im Spielstand');
console.log('Valdoria-Laufzeit geprüft: Tiefensysteme, Haushalt, Feste, Rivalen, Palast, Gesellschaft, Gesetze, Expeditionen und Vermächtnis simulieren.');
